name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      DATABASE_URI: skip
      DATABASE_PORT: 27017
      DATABASE: HRIS-M
      SERVER_PORT: 3269
      EMAIL_PORT: 587
      EMAIL_USERNAME: skip
      EMAIL_PASSWORD: skip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build backend
        run: |
          chmod +x ./mvnw
          ./mvnw clean package
